default_platform(:ios)

platform :ios do
  desc "Compilar y subir a TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true,
      in_house: false
    )

    match(
      type: "appstore",
      api_key: api_key,
      readonly: false,
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"]
    )

    increment_build_number(
      xcodeproj: "Runner.xcodeproj",
      build_number: ENV["GITHUB_RUN_NUMBER"]
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.etnya.pilates" => "match AppStore com.etnya.pilates"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end